// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4N-gNqDB61TdG8LLaZ82Fuj2Bdj2yOxg',
    appId: '1:699499151200:web:47500e35f363cc717ce805',
    messagingSenderId: '699499151200',
    projectId: 'maps-b171f',
    authDomain: 'maps-b171f.firebaseapp.com',
    storageBucket: 'maps-b171f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAab_L77TJhXEc5BqtYh0fui-eqzx4GfQ',
    appId: '1:699499151200:android:96f71aedde895b6f7ce805',
    messagingSenderId: '699499151200',
    projectId: 'maps-b171f',
    storageBucket: 'maps-b171f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALdlueWRvBTYcic6IIqnwwnZvg1o_ehe4',
    appId: '1:699499151200:ios:675e7c21b0102abc7ce805',
    messagingSenderId: '699499151200',
    projectId: 'maps-b171f',
    storageBucket: 'maps-b171f.appspot.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALdlueWRvBTYcic6IIqnwwnZvg1o_ehe4',
    appId: '1:699499151200:ios:bba53e0a544a58627ce805',
    messagingSenderId: '699499151200',
    projectId: 'maps-b171f',
    storageBucket: 'maps-b171f.appspot.com',
    iosBundleId: 'com.example.sample.RunnerTests',
  );
}
